# Changes here will be overwritten by Copier
_commit: v6.4.0-13-g15a9227
_src_path: .
author_mail: anonymous@example.org
author_name: Anonymous Person
github_page: ''
project_description: My generic project.
project_slug: generic-project
project_type: generic
pypi: false

