# https://taskfile.dev
---
version: '3'

vars:
  PLUGIN_DIR: cmem-plugin-awesome
  TEMPLATE_REVISION:
    sh: git rev-parse HEAD

tasks:

  default:
    summary: |
      Just a list of documented tasks.
    silent: true
    cmds:
      - task --list

  clean:
    desc: clean up working directory
    cmds:
      - rm -rf {{.PLUGIN_DIR}}

  create:
    desc: create plugin directory with current version and ask for answers
    deps:
      - clean
    cmds:
      - copier copy --vcs-ref {{.TEMPLATE_REVISION}} . {{.PLUGIN_DIR}}

  generate:
    desc: create plugin directory from the current version and default answers
    deps:
      - clean
    cmds:
      - copier copy --vcs-ref {{.TEMPLATE_REVISION}} --defaults . {{.PLUGIN_DIR}}
      - git config --global init.defaultBranch develop
      - git init {{.PLUGIN_DIR}}
      - cd {{.PLUGIN_DIR}} && git add .
      - cd {{.PLUGIN_DIR}} && git config init.defaultBranch main
      - cd {{.PLUGIN_DIR}} && git config user.name "Anonymous Person"
      - cd {{.PLUGIN_DIR}} && git config user.email "anonymous@example.org"
      - cd {{.PLUGIN_DIR}} && git commit -m "init from template"

  check:
    desc: create plugin with default answers and run check
    deps:
      - generate
    cmds:
      - cd {{.PLUGIN_DIR}} && poetry update
      - cd {{.PLUGIN_DIR}} && task check

