---
default:
  image: docker-registry.eccenca.com/eccenca-python:v3.11.4
  # all jobs can be interrupted in case a new commit is pushed
  interruptible: true
  before_script:
    # make sure poetry creates virtual environment as .venv
    - poetry config virtualenvs.in-project true
  cache:
    # cache the virtual environment based on the poetry lock file
    key:
      files:
        - poetry.lock
    paths:
      - .venv

stages:
  - install
  - test
  - build
  - publish

dependencies:
  stage: install
  script:
    - task poetry:install
    - task check:dependencies

bandit:
  stage: test
  needs:
    - dependencies
  script:
    - task check:bandit
  artifacts:
    when: always
    reports:
      junit:
        - dist/junit-bandit.xml

flake8:
  stage: test
  needs:
    - dependencies
  script:
    - task check:flake8
  artifacts:
    when: always
    reports:
      junit:
        - dist/junit-flake8.xml

mypy:
  stage: test
  needs:
    - dependencies
  script:
    - task check:mypy
  artifacts:
    when: always
    reports:
      junit:
        - dist/junit-mypy.xml

pylint:
  stage: test
  needs:
    - dependencies
  script:
    - task check:pylint
  artifacts:
    when: always
    reports:
      junit:
        - dist/junit-pylint.xml

pytest:
  stage: test
  needs:
    - dependencies
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  script:
    - task check:pytest
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: dist/coverage.xml
    paths:
      - dist/badge-coverage.svg
      - dist/badge-tests.svg
      - dist/coverage
      - dist/coverage.xml

safety:
  stage: test
  needs:
    - dependencies
  script:
    - task check:safety

build:
  stage: build
  needs:
    - bandit
    - mypy
    - pytest
    - safety
  script:
    - task build
  artifacts:
    when: always
    paths:
      - dist/*.tar.gz
      - dist/*.whl

pypi:
  # publishing only available on a tag
  stage: publish
  needs:
    - flake8
    - pylint
    - build
  allow_failure: true
  when: manual
  script:
    - poetry config pypi-token.pypi $PYPI_TOKEN
    - poetry publish

