---
name: check

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" and "develop" branch
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install and configure poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: install copier
        run: |
          python3 -m pip install --user copier

      - name: create plugin with default answers and run check
        env:
          CMEM_BASE_URI: ${{ secrets.CMEM_BASE_URI }}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
        run: |
          task check

      - name: Publish Test Report in Action
        uses: mikepenz/action-junit-report@v3
        if: always()  # always run even if the previous step fails
        with:
          report_paths: cmem-plugin-awesome/dist/junit-*.xml

      - name: Publish Test and Coverage Report as PR comment
        uses: xportation/junit-coverage-report@main
        if: github.event_name == 'pull_request'
        with:
          junit-path: cmem-plugin-awesome/dist/junit-pytest.xml
          coverage-path: cmem-plugin-awesome/dist/coverage.xml

